ocp3rook/readme.adoc
Changed links to download rook yaml files to be from this repo.
=> updated labguide readme.adoc

ocs4-registry/README.md
Adding new folder for registry training content.
=> add new folder for ocs4-register workload training

ocp4ocs4/ocs4.adoc
=> Ocs42 fix3

misc/ansible-deployment/README.md, misc/ansible-deployment/add_machinesets.yml, misc/ansible-deployment/check_nodes.yml, misc/ansible-deployment/create_ocs_cluster.yml, misc/ansible-deployment/install_ceph_tools.yml, misc/ansible-deployment/install_ocs_operator.yml, misc/ansible-deployment/ocs_deploy.yml
Set of scripts to deploy OCS on OCP4.2.
Lengthier than the bash script from Chris, but more verbose and more cheks.
Split into several playbooks for easy reuse.
=> Ansible deployment

ocp4ocs4/ocs4.adoc
=> Add section to teach PV <-> RBD mapping

ocp4ocs4/ocs4.adoc
This adds some Ceph commands and explanation to the scale-out section.
Resolves #72
=> Add Ceph verification steps to scale-out section

ocp4ocs4/ocs4.adoc
=> Move the Noobaa CLI client section to the Appendix

ocs4registry/README.md, ocs4registry/registry.adoc
=> Registry marcelh

ocs4registry/registry.adoc
* Remove execute tag from outputs
* Add yaml tag to yaml output
* Convert notes to boxes (renders better in Github)
* Remove $ from commands
=> Fix registry workload

CONTRIBUTING.adoc, modd.conf, ocp4ocs4/ocs4.adoc
Fix some settings in the doc header to activate source highlighting... Sadly this doesn't add much color to the commands but helps a lot in reading the json/yaml output
=> Source highlight

ocs4postgresql/PostgreSQL.adoc, ocs4postgresql/README.adoc, ocs4postgresql/README.md, ocs4postgresql/create_ocs_postgresql_template
Please merge the sagy-postgresql branch. This small lab is ready.
=> Sagy postgresql

ocp4ocs4/obc_app_example.yaml, ocp4ocs4/ocs4.adoc
Using a s3cmd container
Resolves #47
=> Add OBC app example

ocp4ocs4/cluster-monitoring-config.yaml, ocp4ocs4/ocs4.adoc
This section replaces 5. Create a new OCP registry using CephFS (Optional) in ocs4.adoc.
=> Adding new Prometheus on OCS section

CONTRIBUTING.adoc, docs/CONTRIBUTING.html, docs/Jenkins.html, docs/PostgreSQL.html, docs/ocs.html, docs/ocs_content.html, docs/ocs_roadshow.html, docs/registry.html, ocp4ocs4/ocs_content.adoc
This makes using this document in different regions possible
Also updated the html pages
Also fixed asciidoctor warnings in CONTRIBUTIONS.adoc
Resolves #76 #116
=> Use new endpoint with region detection

ocp4ocs4/local-storage.adoc, ocp4ocs4/yamls/cluster-service-AWS.yaml, ocp4ocs4/yamls/cluster-service-VMware.yaml, ocp4ocs4/yamls/cluster-service-metal.yaml
=> Local storage cblum additions

ocp4ocs4/local-storage-byid.adoc, ocp4ocs4/yamls/cluster-service-AWS-expand.yaml
Added new content for /dev/disk/by-id usage and expanding storage by adding devices.
=> New local-storage-byid.adoc

.github/workflows/asciibuild.yml
This should fix the html build pipeline
=> Do not try to render unavailable files

ocp4ocs4/device-fail-replace.md
This is intended to be a working document to collaborate on OSD removal. Please comment and add suggestions, but not intended for merge.
=> Document for removal of an OSD from OCS on bare metal

ui/css/site.css
=> Use full width to render ASCIIdoc content

training/modules/ocs4/nav.adoc, training/modules/ocs4/pages/ocs4-enable-rgw.adoc
This is the doc for:
- Enabling RGW
- Create Service and Route as needed
- Deploy Ceph toolbox to interact with the RGW
- Examples on how to create users
=> RGW enablement documentation

.github/CODEOWNERS, training/modules/ocs4/pages/ocs.adoc, training/modules/ocs4/pages/ocs4-enable-rgw.adoc, training/modules/ocs4/partials/deploy_toolbox.adoc
Use partials for the deploy Toolbox section
=> Dive into partials

training/modules/infra-nodes/pages/ocs4-infra-nodes.adoc
=> fix asciidoc formatting

training/modules/ocs4/pages/ocs4-multisite-replication.adoc
Minor fix to Failover create velero backup section for excluding configmap resource as well as OCS->>ODF.
=> Change OCS to ODF

training/modules/ocs4/pages/ocs4-encryption.adoc
Formatting and instructions for replacement text in yaml.
=> PVC SA Replacement text details

training/modules/ocs4/pages/odf410-multisite-ramen.adoc
Update is result of schedulingIntervals being a list of values which enables having more than a single VolumeReplicationClass with replication interval.
=> Update RDR doc MirroPeer, DRPolicy and DRPC sections

training/modules/ocs4/pages/odf4-metro-ramen.adoc
Need to change order of node reboot and modifying DRPolicy for failback action. Other minor changes made as well in Overview, etc.
=> Metro DR doc changes to disable fencing section

training/modules/ocs4/pages/ocs4-enable-rgw.adoc
Replace shell pipes with oc jsonpath specs
=> Update ceph toolbox rsh and exec commands
